Vagrant.configure('2') do |config|
  config.vm.box = 'spigell/k3os'
  config.vm.box_version = "0.20.11"
  config.vm.guest = :linux

  config.ssh.forward_agent = true
  config.vm.network 'forwarded_port', guest: 22, host: 2222, disabled: true
  config.vm.synced_folder '.', '/vagrant', disabled: true


  config.vm.provider 'virtualbox' do |vb|
    vb.customize ['modifyvm', :id, '--nic2', 'hostonly']
    vb.customize ['modifyvm', :id, '--hostonlyadapter2', 'vboxnet0']

    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
  end
end

