Vagrant.configure('2') do |config|
  config.vm.guest = :linux

  config.ssh.forward_agent = true
  config.vm.network 'forwarded_port', guest: 22, host: 2222, disabled: true
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision 'shell',
    upload_path: '/home/rancher/vagrant-shell',
    inline: 'k3os --version',
    run: 'always'

  config.vm.define 'local' do |local|
    local.vm.box = 'k3os-local.box'
  end

  config.vm.define 'cloud' do |cloud|
    cloud.vm.box = 'spigell/k3os'
  end

end

